apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: deepforge
  labels:
    app: tempo
spec:
  selector:
    app: tempo
  ports:
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: tempo-api
    port: 3200
    targetPort: 3200
    protocol: TCP
  type: ClusterIP