apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: deepforge
data:
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        url: http://tempo-service:3200
        access: proxy
        isDefault: true